# Generated by Django 5.2.12 on 2026-04-24 05:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('MANDATORY', 'Mandatory'), ('PROFILE', 'Profile')], max_length=16)),
                ('duration_sec', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='exam_subjec_slug_aa6c6a_idx'), models.Index(fields=['type'], name='exam_subjec_type_e6e277_idx')],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exam.subject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('ordering', 'Ordering')], max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam/problems/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='exam/problems/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('options', models.JSONField(default=list)),
                ('correct', models.JSONField(default=list)),
                ('score', models.IntegerField(default=1, editable=False)),
                ('explanation', models.CharField(max_length=512)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='exam.module')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['module'], name='exam_proble_module__3cb5bc_idx'), models.Index(fields=['type'], name='exam_proble_type_b44da4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score', 1)), name='exam_problem_score_fixed_one')],
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['subject'], name='exam_module_subject_9d5e87_idx'),
        ),
    ]
