# Generated by Django 6.0.2 on 2026-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_created_at_lesson_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Lesson content in TipTap editor format (JSON).'),
        ),
    ]
